### ISSUE TITLE
Signal bug

### ISSUE THREAD

**Issue by Fanda36** [voxeltycoon/bug-tracker#232] opened 2021-04-21 18:44 UTC
**Describe the bug**
The signal is red but should be green.

**Steps to reproduce**
Steps to reproduce the behavior.

**Build version**
Version information can be found at the bottom of the settings window.

**Platform**
Linux Manjaro 

**Reproducibility**
Every time

**Logs/saves**
Attach [logs or saves](https://github.com/voxeltycoon/bug-tracker/blob/master/README.md#logs) if applicable.

![image](https://user-images.githubusercontent.com/3972954/115604693-f2378c00-a2e1-11eb-905e-cc1553d916e5.png)
[Player.log](https://github.com/voxeltycoon/bug-tracker/files/6353169/Player.log)
[pqlrbenzqlt.zip](https://github.com/voxeltycoon/bug-tracker/files/6353173/pqlrbenzqlt.zip)

**Comment by katepolak** [comment] 2021-04-22 18:45
This is a known issue with the current rail network implementation. The cause is that the diagonal roads are too close to each other so they count as the same signal block. This is unlike to be changed before the big road and rail network mentioned in the post-launch FAQ.

Closing as it's a duplicate of #63

**Closed as completed by katepolak** 2021-04-22 18:45 UTC
