### ISSUE TITLE
Vehicle going from road station to itself when in range of train station and building

### ISSUE THREAD

**Issue by Alastor-git** [voxeltycoon/bug-tracker#207] opened 2021-04-17 01:20 UTC
**Describe the bug**
If a city building is out of range of a train station, it is possible to create a road station that's in range of the building and of the train station. But then, you have to create a route that goes from the station to itself, resulting in an immobile car that just loads and unloads. It looks a bit stupid. 
I expect a car shouldn't be required in this situation. 

**Steps to reproduce**
 - Have city building appear slightly out of range of train station
 - Setup road station  in range of both. 
 - Have car go from station to station to supply the building. 

**Build version**
0.85.0.24 steam

**Platform**
windows 10

**Comment by katepolak** [comment] 2021-04-17 10:08
This is currently the intended behaviour, though it is likely to be changed in the future. If you have ideas for how this could be solved I suggest posting them on the suggestion tracker instead, ideally as a comment to the existing issue voxeltycoon/suggestions#17 

I will close this issue now.

**Closed as completed by katepolak** 2021-04-17 10:08 UTC
Labels: not a bug
