### ISSUE TITLE
signals are stopping trains when they should not 

### ISSUE THREAD

**Issue by SkyverNL** [voxeltycoon/bug-tracker#66] opened 2019-06-28 22:13 UTC
**Describe the bug**
A clear and concise description of what the bug is. If applicable, add screenshots or video to help explain your problem.

![Screenshot (9)](https://user-images.githubusercontent.com/45534586/60373952-64025f80-9a02-11e9-91ca-bda795a5d5ea.png)

using a signal makes trains lose there way even if the signal is faced the other way 

**Steps to reproduce**

make a stop but put 2 tracks to it put a signal to make sure only one train can be there at anytime and the train will lose its way 

**build**
0.71 2019-06-26 itch pre alpha

**Platform**
windows 10 1902

**Reproducibility**
every time

**Comment by victorleblais** [comment] 2019-06-29 00:26
**This is not a bug.**

On your screenshot, the train has nowhere to go. He is trying to go towards the signals, which are facing the opposite way, but if you put signals on only one side of the rails, this makes them one-way, so trains won't be able to cross them from the other side.

If you want to make those tracks two-way, put signals on both sides of the track.
Alternatively, you can make each track one-way, but in one direction each. See the following screenshot for an example of both:
![image](https://user-images.githubusercontent.com/4365075/60377494-04af4a00-9a18-11e9-85e7-c8c9c4aba2a3.png)



Note that there is an indication of where to put the other signal to make it two-way. Notice the green dot here: 
![image](https://user-images.githubusercontent.com/4365075/60377284-aed9a280-9a15-11e9-98d2-21580c1e4f47.png)

**Comment by katepolak** [comment] 2019-06-29 09:06
Closing the issue as it was explained above.

@victorleblais would you mind if we used your images on a wiki page? We might make our own but also might not.

**Closed as completed by katepolak** 2019-06-29 09:06 UTC

**Comment by victorleblais** [comment] 2019-06-29 13:12
@polak-jan Go ahead ! Feel free to reuse them for whatever you want.
