### ISSUE TITLE
Train/truck stops on road when sent to depot

### ISSUE THREAD

**Issue by Bogarn** [voxeltycoon/bug-tracker#127] opened 2019-07-30 11:48 UTC
Train or truck which is sent to depot for maintenance with the "Go for maintenance" button simply stop where they are, their speed slowly decreases to zero. After a while they just disappear and appear in the depot which they were sent to. It looks like it takes the same time as if they kept traveling along the road/rail to the depot.

**Comment by katepolak** [comment] 2019-07-30 11:53
I don't see anything about what you said that is a bug. Vehicles teleporting to depots is an intended behaviour not a bug. A proper pathfinding based behaviour will be introduced at some point.

**Closed as completed** 2019-07-30 11:53 UTC

**Comment by Bogarn** [comment] 2019-07-30 11:54
Ohh okay, sorry I didn't know about that, my fault. I just bought the game few hours ago 'cause I fell in love with the graphics and OpenTTD like style. I know it's pre-alpha state but this behavour felt weird to me.
