### ISSUE TITLE
You can sell items to store in locked region.

### ISSUE THREAD

**Issue by Kpa6i** [voxeltycoon/bug-tracker#149] opened 2019-09-04 07:40 UTC
**Describe the bug**
When the store in a locked region to close to the border, you can place a terminal and move items to it and they will be sell in the store. 

**Steps to reproduce**
Find a store in locked region that will be close to your region. Place a terminal on the border of both regions. Tell track to move items to that terminal. Profit... you are a contabander...

**Build version**
0.76 (August 30, 2019)

**Platform**
Ubuntu 18.04

**Reproducibility**
All times.
![Screenshot from 2019-09-04 10-28-38](https://user-images.githubusercontent.com/1592819/64235127-60a6bb00-cf00-11e9-878e-471a03e11358.jpg)

**Comment by Kpa6i** [comment] 2019-09-04 07:41
It may be a feature, not a bag, if items will have a x1.5 or x2 rate when selling to locked regions

**Comment by victorleblais** [comment] 2019-09-23 08:41
It's not an intended behavior.

The point of selling stuff to a city is to grow it in order to have more store to sell to. If it's in a locked region, chances are you won't be able to access other stores. It's definitely not a "good way" to develop a city.

**Comment by katepolak** [comment] 2019-09-24 20:16
Pretty sure those cities don't get simulated so it won't grow them. At the same time the store won't actually realize that it's being supplied and will never drop it's price.

I might be wrong though.

**Comment by andrewpey** [comment] 2020-06-03 22:28
Fixed in [0.84](https://voxeltycoon.xyz/changelog#0.84).

**Comment by andrewpey** [comment] 2020-06-03 22:29
Fixed in [0.84](https://voxeltycoon.xyz/changelog#0.84).

**Closed as completed by andrewpey** 2020-06-03 22:28 UTC
