### ISSUE TITLE
Black builds / Building Asset not loading correctly?

### ISSUE THREAD

**Issue by hasezoey** [voxeltycoon/bug-tracker#110] opened 2019-07-06 19:06 UTC
**Describe the bug**
these black buildings
![black buildings](https://i.imgur.com/Y56IV7K.png)

**Steps to reproduce**
let a City build buildings

**Build version**
0.72

**Platform**
- Linux Mint 19.1
- Kernel 5.0.21

**Reproducibility**
often, but only if a city builds

Note: i dont have any mods installed that add buildings

**Comment by katepolak** [comment] 2019-08-03 08:58
On the screenshot it seems like only a single type of building is affected. That would be pointing to it being either caused by you editing some files or the files being corrupted. Can you please confirm whether this happens on other versions as well?

**Comment by hasezoey** [comment] 2019-08-03 10:39
> That would be pointing to it being either caused by you editing some files or the files being corrupted.

i didnt modify any files, and as far as i know, i dont have any house-adding mods installed

---

yes i can confirm that it happenes on 73, 74, 75 too
note:
- upgraded from kernel 5.0.21(uuku) to 5.0.0-23(mintupdate)

PS: i dont know if this infomation is important, but i forgot the add it in the original post:
i am using amgpu driver (AMD Vega 64)

**Comment by katepolak** [comment] 2019-08-04 15:45
How have you updated to the new versions?

**Comment by hasezoey** [comment] 2019-08-04 16:00
> How have you updated to the new versions?

- which versions? Voxel Tycoon later than 0.75? i cant find anything later
- if you mean kernel, 5.1, 5.2 dosnt work on my maschine
- when you mean amdgpu driver, it uses the kernel standard (i dont know how to update them manually)

**Comment by katepolak** [comment] 2019-08-04 16:56
I asked HOW you updated. Ans I meant the game, sorry for not being clear on that.

**Comment by hasezoey** [comment] 2019-08-04 17:06
> I asked HOW you updated. Ans I meant the game, sorry for not being clear on that.

updated via itch.io update (game settings -> Manage -> Check for Updates -> click on the update button)
(and my first every install of the game was on 0.72, where these problems were already present)

**Comment by katepolak** [comment] 2019-08-04 19:35
That's quite weird than. Have you tried reinstalling the game? If that doesn't help than I am pretty clueless.

The issue happening here is the UV mapping not being loaded correctly. What leads me to believe that it's a file related issue is that from what I can tell it's always the same building.

**Comment by hasezoey** [comment] 2019-08-04 19:43
> Have you tried reinstalling the game?

will try that, but cant today anymore, sorry

**Comment by katepolak** [comment] 2019-08-04 19:49
Don't worry. Are you 100% sure you don't have any mods? Because I have looked through the base game files and there is no house that looks even remote like the one you have on your picture.

**Comment by hasezoey** [comment] 2019-08-04 19:51
i had these where i dont had any mods installed
now i have, but i dont know any mod that adds housing, from the ones i have installed

**Comment by hasezoey** [comment] 2019-08-05 11:41
reinstalled the game now (itch.io -> game settings -> reinstall), its still happening

like i said, it happened where i didnt have *any* mods installed, now i have, but i dont know any of them adding housing
anyway here is a modlist
<details><summary>Modlist</summary><p>

```json
[
  {
    "Author": "Golden Arrow",
    "Updated": "2019-07-01T16:38:41.448Z",
    "Disabled": false,
    "Name": "goldenarrow-australia"
  },
  {
    "Author": "TransCanadaLimited",
    "Updated": "2019-07-01T02:27:07.931Z",
    "Disabled": false,
    "Name": "tclm-line"
  },
  {
    "Author": "TransCanadaLimited",
    "Updated": "2019-07-01T02:26:16.49Z",
    "Disabled": false,
    "Name": "tclrs3"
  },
  {
    "Author": "TransCanadaLimited",
    "Updated": "2019-07-01T02:24:51.225Z",
    "Disabled": false,
    "Name": "tclsd40"
  },
  {
    "Author": "TransCanadaLimited",
    "Updated": "2019-07-01T02:24:05.161Z",
    "Disabled": false,
    "Name": "tclsteam"
  },
  {
    "Author": "TransCanadaLimited",
    "Updated": "2019-07-01T02:23:36.286Z",
    "Disabled": false,
    "Name": "tclsupercontinental"
  },
  {
    "Author": "Golden Arrow",
    "Updated": "2019-06-30T17:15:22.822Z",
    "Disabled": false,
    "Name": "goldenarrow-germany"
  },
  {
    "Author": "Golden Arrow",
    "Updated": "2019-07-01T19:11:24.467Z",
    "Disabled": false,
    "Name": "goldenarrow-base"
  },
  {
    "Author": "LemonGem3021668",
    "Updated": "2018-12-21T07:09:31.478Z",
    "Disabled": false,
    "Name": "wpf_pk"
  },
  {
    "Author": "TransCanadaLimited",
    "Updated": "2019-07-03T00:59:48.319Z",
    "Disabled": false,
    "Name": "tclsignals2"
  },
  {
    "Author": "TransCanadaLimited",
    "Updated": "2019-07-02T18:05:15.773Z",
    "Disabled": false,
    "Name": "tclfreight"
  },
  {
    "Author": "Trololol Gaming",
    "Updated": "2018-09-23T22:13:42.216Z",
    "Disabled": false,
    "Name": "c40-8w"
  },
  {
    "Author": "Trololol Gaming",
    "Updated": "2018-11-03T18:47:28.183Z",
    "Disabled": false,
    "Name": "nyc_gp40_3"
  },
  {
    "Author": "Trololol Gaming",
    "Updated": "2018-11-25T18:05:40.318Z",
    "Disabled": false,
    "Name": "21st_century_limited"
  },
  {
    "Author": "TransCanadaLimited",
    "Updated": "2019-07-01T02:32:33.219Z",
    "Disabled": false,
    "Name": "tclge"
  },
  {
    "Author": "TransCanadaLimited",
    "Updated": "2019-07-01T02:31:32.251Z",
    "Disabled": false,
    "Name": "tclgf6c"
  },
  {
    "Author": "TransCanadaLimited",
    "Updated": "2019-07-01T02:28:37.181Z",
    "Disabled": false,
    "Name": "tclgp30"
  },
  {
    "Author": "TransCanadaLimited",
    "Updated": "2019-07-01T02:31:06.197Z",
    "Disabled": false,
    "Name": "tclgn"
  },
  {
    "Author": "TransCanadaLimited",
    "Updated": "2019-07-01T02:28:03.928Z",
    "Disabled": false,
    "Name": "tclgp9"
  },
  {
    "Author": "meinroman",
    "Updated": "2019-07-05T18:18:17.875Z",
    "Disabled": false,
    "Name": "mr0_pack"
  },
  {
    "Author": "TransCanadaLimited",
    "Updated": "2019-07-01T02:18:12.479Z",
    "Disabled": false,
    "Name": "tclswitchers"
  },
  {
    "Author": "vncnt",
    "Updated": "2018-09-04T19:19:06.175Z",
    "Disabled": false,
    "Name": "oebb"
  },
  {
    "Author": "Golden Arrow",
    "Updated": "2019-07-10T18:45:34.651Z",
    "Disabled": false,
    "Name": "goldenarrow-portugal"
  },
  {
    "Author": "Golden Arrow",
    "Updated": "2019-07-10T18:45:23.797Z",
    "Disabled": false,
    "Name": "goldenarrow-france"
  },
  {
    "Author": "Golden Arrow",
    "Updated": "2019-07-12T16:20:13.84Z",
    "Disabled": false,
    "Name": "goldenarrow-united kingdom"
  }
]
```
</p></details>

**Comment by andrewpey** [comment] 2019-08-20 23:43
Could you zip the entire game folder and upload somewhere (like https://mega.nz/) please?

**Comment by hasezoey** [comment] 2019-08-21 02:47
[here, includes game+mods and config+saves](https://drive.google.com/drive/folders/1oZF6LaWZyAuL_j2G2rj_CUNq6ywnZBAH?usp=sharing)

extra info: upgraded to latest version, and loaded saves, still happening
(note for the analytics "cannot reach" errors: i use pihole)

EDIT: both finished uploading now

**Comment by andrewpey** [comment] 2019-08-23 00:56
Thanks, I'll give it a look.

**Comment by andrewpey** [comment] 2019-08-23 01:36
Ok, the building seems to be this:
![image](https://user-images.githubusercontent.com/1748681/63560545-123c0880-c55f-11e9-875a-3a027615dec1.png)

It's `northbrook approach.house` from `goldenarrow-base`, so it definitely comes with the mod, not the base game.

But on my machine, it loaded without an issue, so what is causing the issue still is not clear.

**Comment by hasezoey** [comment] 2019-08-23 01:41
@andrewpey sorry, didnt know this - i tough i didnt have *any* mods that adds housing...

so close as "not an bug with the base game" / "bug from mod"?

**Comment by andrewpey** [comment] 2019-08-23 02:04
No problem.

Could you try to replace your `Content/goldenarrow-base/houses/Northbrook Approach (House)/Northbrook Approach.obj` with [this one ](https://github.com/voxeltycoon/bug-tracker/files/3532539/Northbrook.Approach.zip) and then try to run the game?

**Comment by hasezoey** [comment] 2019-08-23 02:13
sorry, didnt fix it

**Comment by andrewpey** [comment] 2019-08-23 02:22
Thanks.

**Comment by andrewpey** [comment] 2020-04-26 02:02
Probably video driver related issue? Unfortunately, there’s no way for us to reproduce it, and it seems it has nothing to do with assets or game logic. Closing for now.

**Closed as completed by andrewpey** 2020-04-26 02:02 UTC
Labels: need info
