### ISSUE TITLE
Load Savegame i get "The given key was not present in the dictionary"

### ISSUE THREAD

**Issue by Ursch** [voxeltycoon/bug-tracker#178] opened 2020-08-26 08:33 UTC
When i load a Savegame from yesterday i got "The given key wos not present in the dictionary".

**Comment by Ursch** [comment] 2020-08-26 08:34
![image](https://user-images.githubusercontent.com/70261139/91280870-aef34080-e787-11ea-965c-2cf559b06782.png)

**Comment by andrewpey** [comment] 2020-08-31 08:14
Is the problem still reproduce? Can we have the [log file](https://github.com/voxeltycoon/bug-tracker/blob/master/README.md#logs)?

**Comment by SMERKIN5000** [comment] 2021-04-24 02:00
I came across this issue and I think I know the reason why. I clicked on a train and selected to move it to a depot and accidentally clicked a garage window instead of a train depot window. The game worked OK at that point however after that they train was always greyed out when I looked at a station. I could never move it back to a depot. When I clicked the link to view the 1st person I saw other trains pass through it and third person it wasn't visible. I saved the game and exited to desktop and then tried to load the game again to see if the train would fix itself. This is when I receive the message reported by this thread. Save file can now no longer be loaded.

[Player.log](https://github.com/voxeltycoon/bug-tracker/files/6368824/Player.log)

**Comment by andrewpey** [comment] 2021-04-26 18:47
Fixed in [0.85.1](https://voxeltycoon.xyz/changelog#0.85.1).

**Closed as completed by andrewpey** 2021-04-26 18:47 UTC
