### ISSUE TITLE
Store will not use resources nearby

### ISSUE THREAD

**Issue by techn1fire** [voxeltycoon/bug-tracker#122] opened 2019-07-21 21:25 UTC
**Describe the bug**
A store located next to a warehouse and terminal with required resource does use the resource.
![Will not use resources](https://user-images.githubusercontent.com/8634442/61597276-6734d980-abc3-11e9-8feb-230a1f41b579.PNG)

**Steps to reproduce**
Store spawns next to warehouse and terminal.

**Build version**
0.74 2019-07-19 ITCH PRE-ALPHA

**Platform**
Windows 10 Pro 1903 (Build 18362.239)

**Reproducibility**
Unknown

**Comment by Headmast** [comment] 2019-07-22 05:51
I have the same problem, it always repeats.

**Comment by victorleblais** [comment] 2019-07-22 07:30
Pretty sure it's intended behavior and not a bug.

**Comment by katepolak** [comment] 2019-07-22 11:56
He has a truck that's transferring them from the warehouse so it should work.

**Comment by techn1fire** [comment] 2019-07-22 15:46
There should be a better way of handling things with local businesses...
![giphy](https://user-images.githubusercontent.com/8634442/61646052-11ad0b00-ac5d-11e9-8cfc-93c3590347e4.gif)

**Comment by katepolak** [comment] 2019-07-23 06:06
What the GIF shows is an intended behaviour for now.

**Closed as completed** 2019-08-20 23:45 UTC
Labels: wontfix
