### ISSUE TITLE
Wrecked vehicles from building freight stations next to them

### ISSUE THREAD

**Issue by asiaclonk** [voxeltycoon/bug-tracker#226] opened 2021-04-20 17:36 UTC
**Describe the bug**
Attaching innate road from a new building to existing roads with vehicles on them will immediately wreck the vehicles

**Steps to reproduce**
Have a road with a vehicle on it. Build a freight station attached to directly next to the vehicle.

**Build version**
0.85.0.24 steam

**Platform**
Windows 10

**Reproducibility**
Always

**Screenshot**
![VoxelTycoon 2021 04 20 19_31_50](https://user-images.githubusercontent.com/16159591/115440157-b6cc8d00-a20f-11eb-944d-b53118f431d3.png)

**Comment by victorleblais** [comment] 2021-04-21 10:50
Duplicate of #108

**Closed as completed by victorleblais** 2021-04-21 10:50 UTC
Labels: duplicate
