### ISSUE TITLE
Pre-signal not detecting a free path

### ISSUE THREAD

**Issue by person3000** [voxeltycoon/bug-tracker#150] opened 2019-10-02 00:52 UTC
**Describe the bug**
The pre-signal isn't detecting a free path despite the path being clear. It is possible this is the same issue as #63 so that might help with solving this?
![EVIDENCE](https://user-images.githubusercontent.com/29667106/66010548-5dfe9d80-e48d-11e9-9a24-0b838e9a8c67.png)

**Steps to reproduce**
Two parallel tracks, with one or both diverging across the other to a third perpendicular track.
Run two trains in opposite directions, both want to go straight through.

**Build version**
0.77 2019-09-12

**Platform**
Windows 10

**Reproducibility**
Every time.

**Comment by drewtato** [comment] 2019-10-02 01:58
This is just how signals work. Both kinds ensure that only one train is in a block at a time. This entire blue part is one block.

![one_block](https://user-images.githubusercontent.com/15526875/66012608-b24d5180-e47c-11e9-87a9-e38ef8a2d88a.jpg)

The two tracks would need to be separated into different blocks by a signal in between, which would require more space.

Also, pre-signals aren't OpenTTD path signals. They're more like Factorio chain signals.

**Comment by person3000** [comment] 2019-10-02 02:00
The description says it'll be yellow if any exit signal is green. I guess it doesn't mean pathing, JUST exits. Thanks for the info, guess I'll go restart again.

**Comment by victorleblais** [comment] 2019-10-15 08:20
I'm closing this issue since this is intended behavior, like @drewtato pointed out.

- A pre-signal is green if all exits are green AND the following block is unoccupied.
- A pre-signal is yellow if at least one exit is green AND the following block is unoccupied.
- A pre-signal is red if all the exits are red OR the following block is occupied.

**Closed as completed by victorleblais** 2019-10-15 08:20 UTC
Labels: not a bug
