### ISSUE TITLE
Demands randomly dying

### ISSUE THREAD

**Issue by EsquimaltNanaimo** [voxeltycoon/bug-tracker#33] opened 2019-05-16 10:33 UTC
**Describe the bug**
After 10+ hours of perfectly fine gameplay, some demands stopped receiving cargo and de-leveled, throwing "Demand Decreased" notifications. They were the two demands that one city started with. Re-loading the save file fixed the problem.

As you can see in the photos, there is a log train (with Full Unload orders) waiting at the platform, doing nothing while the demand it's meant to serve decays. It was fine until it randomly stopped.

![1-1](https://user-images.githubusercontent.com/34557490/57847409-3f706200-778b-11e9-889a-44e30a161687.png)
![1-2](https://user-images.githubusercontent.com/34557490/57847421-45664300-778b-11e9-8600-afb01a724f61.png)

**Steps to reproduce**
Unknown.

**Build version**
0.55

**Platform**
Microsoft Windows 7

**Reproducibility**
Unknown.

**Comment by goldenarrow** [comment] 2019-05-17 16:08
I've noticed things can sometimes be a bit confusing if you fulfil the storage and a train arrives and tries to unload and can't. Was this only on wood or both the word and iron ore? I ask because I'm curious what the warehouse stores. 

If the demand has taken the maximum storage (290) and the warehouse accepts wood, it might try to store the wood in the warehouse. If the warehouse is full, it will keep trying to fill that until you re-load the save file (or change the train's orders).

If the warehouse stores something else, I'm (heh) stumped.

**Comment by EsquimaltNanaimo** [comment] 2019-05-18 17:28
The warehouse is for iron bar transfers, to a demand that's slightly too far away from the station. Unrelated to the iron ore and wood log demands.

**Comment by andrewpey** [comment] 2019-08-02 22:42
Should be fixed since then, feel free to reopen if reproduced.

**Closed as completed by andrewpey** 2019-08-02 22:42 UTC
