### ISSUE TITLE
Asset Editor: Can't edit hex color, modifier buttons stopped working

### ISSUE THREAD

**Issue by goldenarrow** [voxeltycoon/bug-tracker#170] opened 2020-06-05 19:42 UTC
**Describe the bug**
Trying to select the Hexidecimal number. Wasn't able to highlight the number or type over it. Instead, Voxel Tycoon crashed out and closed itself.

Entered the Asset Editor after restarting the game, still unable to Shift and Click to add colours to the options OR enter an exact hexidecimal number.

Player.log file attached below.

**Steps to reproduce**
Open Asset Editor.
Try to select the Hexidecimal number.

**Build version**
0.84

**Platform**
Windows 10

**Reproducibility**
Every time.

[Player.log](https://github.com/voxeltycoon/bug-tracker/files/4738139/Player.log)

**Comment by andrewpey** [comment] 2020-06-06 13:36
Thanks, we'll look into that.

**Comment by andrewpey** [comment] 2020-06-06 13:44
Can't reproduce the crash (also there's nothing in the logs indicating it happened), but other symptoms are there.

We'll deploy a fix soon.

**Comment by goldenarrow** [comment] 2020-06-06 14:40
Thanks! 

I've tried to recreate the first error message and I _think_ I know it's cause.

If trying to select the Hexidecimal number for a long period of time and trying to copy it, my PC throws up a Windows 10 warning message that VT is failing to respond. 

I must have accidentally closed it from that - but I didn't even see the Windows 10 warning message pop up first time.

**Comment by andrewpey** [comment] 2020-06-06 14:46
I see, thanks.

**Comment by andrewpey** [comment] 2020-06-06 20:31
Fixed in [0.84.1](https://voxeltycoon.xyz/changelog#0.84.1).

**Closed as completed by andrewpey** 2020-06-06 20:31 UTC
