### ISSUE TITLE
Error when attempting to rebind the "pause game" key

### ISSUE THREAD

**Issue by Alastor-git** [voxeltycoon/bug-tracker#222] opened 2021-04-18 15:46 UTC
**Describe the bug**
When attempting to rebind "pause game" to the square key on the left of 1 on an  AZERTY keyboard, the config menu got blocked and game generated the attached report. 

**Steps to reproduce**
 - Open configuration menu
 - click on the key binding of "pause game"
 - press the square key. 

**Build version**
0.85.0.24 steam

**Platform**
Windows 10

**Reproducibility**
How often an issue reproduces: every time, often, rare, once.

**Logs/saves**
[Player.log](https://github.com/voxeltycoon/bug-tracker/files/6331614/Player.log)

**Comment by Alastor-git** [comment] 2021-04-18 15:49
Playing with it a little bit more, it actually subsequently does the same for every attempt to bind a key, except in those cases, it does bind the key.

**Comment by victorleblais** [comment] 2021-04-18 15:49
Probably related to #191

**Comment by Alastor-git** [comment] 2021-04-18 15:51
It does sound like the same issue indeed. Sorry, I didn't find it initially.

**Comment by katepolak** [comment] 2021-04-18 15:52
Does that specific key not work in any key bind or is the controls window broken altogether? I don't personally have AZERTY installed so I can't test it quickly but I doubt a specific key could cause this.

**Comment by Alastor-git** [comment] 2021-04-18 15:59
I tested it again. It does display ' instead of ², which led me to initially assume that it didn't work since the rest of the window broke, but it did assign the key. 
So the key binding works but the window breaks after any 1 key assignment.

**Comment by katepolak** [comment] 2021-04-18 16:00
Based on that description it indeed looks like a duplicate of #191 so I will close this issue in favour of that one. Thank you for the quick updates

**Closed as completed by katepolak** 2021-04-18 16:00 UTC
Labels: duplicate, ui
