### ISSUE TITLE
Vehicles Sent to Depot Come to Stand Still In Road

### ISSUE THREAD

**Issue by JonathanAspeling** [voxeltycoon/bug-tracker#217] opened 2021-04-18 10:48 UTC
**Describe the bug**
I commissioned several iron ore/coal trucks to return to the Depot. The trucks came to a stand still in the road. I managed to clear the event by: Deleting their routes. The trucks then teleported to the Depot where they could be sold. 

Was expecting them to drive to depot and enter it and then be available to be sold. 

**Steps to reproduce**
Load Save Game - Find Venture South Station - See string of trucks just standing still along road to Lak Havasu City.

**Build version**
V0.85.0.24 steam

**Platform**
Windows 10 

**Reproducibility**
How often an issue reproduces: every time

**Logs/saves**
[07uo2ou144e.zip](https://github.com/voxeltycoon/bug-tracker/files/6331057/07uo2ou144e.zip)

**Comment by katepolak** [comment] 2021-04-18 10:51
How long did you wait before you deleted the route? The current behaviour for the "Send to depot" command is that the vehicle will stop and teleport, and the time it stays stopped depends on how far away from the depot it is. So you most likely simply didn't wait for long enough.

This will be changed pretty soon to make them drive to the depot instead. But I am marking this as "not a bug" and closing.

**Closed as completed by katepolak** 2021-04-18 10:51 UTC
Labels: not a bug
