### ISSUE TITLE
train is lost on track

### ISSUE THREAD

**Issue by evinxnl** [voxeltycoon/bug-tracker#200] opened 2021-04-16 17:59 UTC
**Describe the bug**
A clear and concise description of what the bug is. If applicable, add screenshots or video to help explain your problem.

**Steps to reproduce**
Steps to reproduce the behavior.

**Build version**
Version information can be found at the bottom of the settings window.

**Platform**
OS name and version.

**Reproducibility**
How often an issue reproduces: every time, often, rare, once.

**Logs/saves**
Attach [logs or saves](https://github.com/voxeltycoon/bug-tracker/blob/master/README.md#logs) if applicable.

[1jdja7cxs0h.zip](https://github.com/voxeltycoon/bug-tracker/files/6327101/1jdja7cxs0h.zip)

**Comment by victorleblais** [comment] 2021-04-16 19:15
The issue comes from the tracks in the mountains.

This is not a valid track, trains can't go on that: 
![image](https://user-images.githubusercontent.com/4365075/115073692-fd14aa00-9ef8-11eb-8794-93d909b8f01f.png)

**Comment by katepolak** [comment] 2021-04-16 19:23
Next time I would recommend asking about things like this somewhere like the official Discord. And when you do make bug reports please fill the information in properly instead of leaving the instructions there.

I will now close this as it's techincally a duplicate of #9

**Closed as completed by katepolak** 2021-04-16 19:23 UTC
Labels: duplicate
