### ISSUE TITLE
[Linux] Zooming in/out inverted in newest build

### ISSUE THREAD

**Issue by felixactually** [voxeltycoon/bug-tracker#6] opened 2019-04-22 19:02 UTC
On the `slow` branch scrolling the mousewheel up (towards your monitor) zooms in and scrolling it down (towards you) zooms out, as expected. However, on the `nightly` branch it is inverted. (Note by Maxim: Possibly related to upgrade to next major Unity version).

**Comment by andrewpey** [comment] 2019-04-22 19:06
Spotted on Linux, not affects Windows.

**Comment by andrewpey** [comment] 2019-04-23 00:03
Not affecting MacOS as well.

**Comment by andrewpey** [comment] 2019-04-27 14:45
Confirmed that this is a regression caused by upgrading to Unity 2019.1 (not reproducible in builds made with 2018.3). Filled a bug report to Unity, currently exploring ways to workaround.

**Comment by andrewpey** [comment] 2019-04-28 14:17
Unity issue: https://issuetracker.unity3d.com/issues/linux-input-dot-mousescrolldelta-returns-reversed-values-in-linux-player

**Comment by andrewpey** [comment] 2019-05-01 20:21
Deployed a workaround in **0.53**. Should work for both zooming and scrolling in lists.

Closing this until Unity will be able to fix it.

**Closed as completed by andrewpey** 2019-05-01 20:21 UTC

**Comment by andrewpey** [comment] 2019-05-15 15:09
Fixed in Unity Unity 2019.3.0a3 (https://issuetracker.unity3d.com/issues/linux-input-dot-mousescrolldelta-returns-reversed-values-in-linux-player). Until then, workaround stays applied.
