### ISSUE TITLE
error generating roads in city

### ISSUE THREAD

**Issue by MaximDementyev** [voxeltycoon/bug-tracker#64] opened 2019-06-28 20:18 UTC
**Describe the bug**
![2019-06-28_23-07-59](https://user-images.githubusercontent.com/15971031/60368676-226db680-99fa-11e9-8a75-d7b83d5e7cfd.png)
![2019-06-28_23-16-34](https://user-images.githubusercontent.com/15971031/60368939-d2432400-99fa-11e9-836e-280fb3212c05.png)

on the left is a long road built by me, a short one generated by the game. road generated too close

on the right, the entire road is automatically generated. the intersection is rendered incorrectly

**Steps to reproduce**
wait for the development of the city, and hope

**Build version**
v0.73 2019-06-26 ITCH_RU PRE_ALPHA
 
**Platform**
windows 10

**Reproducibility**
often

**Comment by katepolak** [comment] 2019-06-28 20:21
Please check if there aren't duplicates before posting bug reports.

Duplicate of #17

**Closed as completed by katepolak** 2019-06-28 20:21 UTC
Labels: duplicate
