### ISSUE TITLE
not clickable building

### ISSUE THREAD

**Issue by sunaneko-1324** [voxeltycoon/bug-tracker#140] opened 2019-08-09 17:57 UTC
**Describe the bug**
not clickable building.

**Steps to reproduce**
click this building.
![image](https://user-images.githubusercontent.com/17085696/62798857-44d71180-bb1a-11e9-87c7-57c71afe8918.png)
It looks like the city menu should open, but I can't click.

**Build version**
0.75

**Platform**
windows 10 pro

**Reproducibility**
every time

**Comment by katepolak** [comment] 2019-08-09 22:52
This building will be used for the power grid feature when it gets introduced. For now it's just a regular building so as far as I can tell there is no unintended behaviour described here.

**Comment by andrewpey** [comment] 2020-06-03 22:28
Fixed in [0.84](https://voxeltycoon.xyz/changelog#0.84).

**Closed as completed by andrewpey** 2020-06-03 22:28 UTC
